version: "2"
services:
  web:
    build: .
    image: tab-nabbers
    command: npm run open:front
    volumes:
      - .:/app/
      - /app/node_modules

    ports:
    - "8080:8080"

  mongo:
    image: "mongo"
    ports:
    - "27017:27017"


  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
    - "1234:1234"